# Generated by Django 6.0.1 on 2026-03-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFetchStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('national', '중앙부처복지서비스'), ('local', '지자체복지서비스'), ('odcloud', '복지서비스정보')], max_length=20)),
                ('fetch_date', models.DateField()),
                ('status', models.CharField(choices=[('success', '성공'), ('failure', '실패')], max_length=10)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '사회서비스 수집 상태',
                'verbose_name_plural': '사회서비스 수집 상태',
                'ordering': ['-fetch_date', 'source'],
                'constraints': [models.UniqueConstraint(fields=('source', 'fetch_date'), name='unique_service_fetch_status_source_date')],
            },
        ),
        migrations.CreateModel(
            name='SocialService',
            fields=[
                ('social_service_id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('national', '중앙부처복지서비스'), ('local', '지자체복지서비스'), ('odcloud', '복지서비스정보')], max_length=20)),
                ('external_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('summary', models.TextField(blank=True)),
                ('detail_url', models.URLField(blank=True)),
                ('site_url', models.URLField(blank=True)),
                ('contact', models.CharField(blank=True, max_length=255)),
                ('ministry', models.CharField(blank=True, max_length=120)),
                ('organization', models.CharField(blank=True, max_length=120)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('base_year', models.PositiveIntegerField(blank=True, null=True)),
                ('region_ctpv', models.CharField(blank=True, max_length=50)),
                ('region_sgg', models.CharField(blank=True, max_length=50)),
                ('support_cycle', models.CharField(blank=True, max_length=80)),
                ('support_type', models.CharField(blank=True, max_length=120)),
                ('apply_method_name', models.CharField(blank=True, max_length=120)),
                ('apply_method_detail', models.TextField(blank=True)),
                ('target_detail', models.TextField(blank=True)),
                ('selection_criteria', models.TextField(blank=True)),
                ('benefit_detail', models.TextField(blank=True)),
                ('welfare_outline', models.TextField(blank=True)),
                ('online_applicable', models.BooleanField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(blank=True, null=True)),
                ('first_registered_at', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('last_modified', models.DateField(blank=True, null=True)),
                ('life_codes', models.CharField(blank=True, max_length=200)),
                ('target_codes', models.CharField(blank=True, max_length=200)),
                ('theme_codes', models.CharField(blank=True, max_length=200)),
                ('life_names', models.CharField(blank=True, max_length=200)),
                ('target_names', models.CharField(blank=True, max_length=200)),
                ('theme_names', models.CharField(blank=True, max_length=200)),
                ('contact_list', models.JSONField(blank=True, default=list)),
                ('homepage_list', models.JSONField(blank=True, default=list)),
                ('law_list', models.JSONField(blank=True, default=list)),
                ('form_list', models.JSONField(blank=True, default=list)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fetched_at'],
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='unique_social_service_source_external_id')],
            },
        ),
    ]
